const CACHE_NAME = "formatperfection-cache-v2";
const urlsToCache = [
  "/",
  "speaker.html",
  "test/Untitled document.pdf",
  "test/Untitled document (1).pdf",
  "test/background.avif",
  "pdfsplitter.js",
  "runner.c",
  "icons/icon-2.png",
  "icons/icon.png",
  "trial.html",
  "tsconfig.json",
  "white-rm.html",
  "path.txt",
  "pdfsplitter.css",
  "pdfmerger.html",
  "pdfeditor.html",
  "painxl.html",
  "add.html",
  "fight.css",
  "suggestions.php",
  "imageconverter.js",
  "pdfmerger.js",
  "rm-background.html",
  "fight.html",
  "pdfmerger.css",
  "pdfeditor.js",
  "assets/UTIF.min.js",
  "assets/pdf-lib.min.js",
  "assets/libheif.js.js",
  "assets/jspdf.umd.min.js",
  "assets/utif/package.json",
  "assets/utif/README.md",
  "assets/utif/LICENSE",
  "assets/utif/UTIF.js",
  "assets/utif/package-lock.json",
  "assets/imagetracer_v1.2.6.js",
  "assets/libheif.js",
  "assets/pdf-lib/dist/pdf-lib.min.js.map",
  "assets/pdf-lib/dist/pdf-lib.min.js",
  "assets/pdf-lib/dist/pdf-lib.esm.js.map",
  "assets/pdf-lib/dist/pdf-lib.js",
  "assets/pdf-lib/dist/pdf-lib.esm.min.js.map",
  "assets/pdf-lib/dist/pdf-lib.js.map",
  "assets/pdf-lib/dist/pdf-lib.esm.js",
  "assets/pdf-lib/dist/pdf-lib.esm.min.js",
  "assets/learngif.txt",
  "assets/pdf.min.mjs",
  "assets/Orbitron.css",
  "assets/gif.js/package.json",
  "assets/gif.js/README.md",
  "assets/gif.js/bin/build",
  "assets/gif.js/bin/version",
  "assets/gif.js/.npmignore",
  "assets/gif.js/index.js",
  "assets/gif.js/dist/gif.js",
  "assets/gif.js/dist/gif.worker.js",
  "assets/gif.js/dist/gif.js.map",
  "assets/gif.js/dist/gif.worker.js.map",
  "assets/gif.js/src/LZWEncoder.js",
  "assets/gif.js/src/benchmark.coffee",
  "assets/gif.js/src/NeuQuant.js",
  "assets/gif.js/src/browser.coffee",
  "assets/gif.js/src/TypedNeuQuant.js",
  "assets/gif.js/src/gif.coffee",
  "assets/gif.js/src/gif.worker.coffee",
  "assets/gif.js/src/GIFEncoder.js",
  "assets/gif.js/site/package.json",
  "assets/gif.js/site/contents/scripts/vendor/mootools.js",
  "assets/gif.js/site/contents/scripts/vendor/ready.js",
  "assets/gif.js/site/contents/scripts/main.coffee",
  "assets/gif.js/site/contents/images/test/test3-orig.jpg",
  "assets/gif.js/site/contents/images/test/anim1.jpg",
  "assets/gif.js/site/contents/images/test/anim4.jpg",
  "assets/gif.js/site/contents/images/test/anim2.jpg",
  "assets/gif.js/site/contents/images/test/test1-ref.gif",
  "assets/gif.js/site/contents/images/test/test2-ref.gif",
  "assets/gif.js/site/contents/images/test/test3-ref.gif",
  "assets/gif.js/site/contents/images/test/test1-orig.jpg",
  "assets/gif.js/site/contents/images/test/test3-orig.png",
  "assets/gif.js/site/contents/images/test/anim3.jpg",
  "assets/gif.js/site/contents/images/test/test2-orig.jpg",
  "assets/gif.js/site/contents/images/test/anim-ref.gif",
  "assets/gif.js/site/contents/images/logo.gif",
  "assets/gif.js/site/contents/images/loading.gif",
  "assets/gif.js/site/contents/index.json",
  "assets/gif.js/site/contents/code.md",
  "assets/gif.js/site/contents/tests/canvas.coffee",
  "assets/gif.js/site/contents/tests/video.coffee",
  "assets/gif.js/site/contents/tests/canvas.md",
  "assets/gif.js/site/contents/tests/clip.mp4",
  "assets/gif.js/site/contents/tests/clip.ogv",
  "assets/gif.js/site/contents/tests/video.md",
  "assets/gif.js/site/contents/robots.txt",
  "assets/gif.js/site/contents/styles/main.less",
  "assets/gif.js/site/contents/styles/vendor/elements.less",
  "assets/gif.js/site/contents/styles/vendor/reset.less",
  "assets/gif.js/site/plugins/jsignore.coffee",
  "assets/gif.js/site/templates/index.html",
  "assets/gif.js/site/templates/layout.html",
  "assets/gif.js/site/templates/test.html",
  "assets/gif.js/site/config.json",
  "assets/gif.worker.js",
  "assets/heic2any.min.js",
  "assets/Font.woff2",
  "assets/gif.min.js",
  "assets/gif-js/package.json",
  "assets/gif-js/LICENSE",
  "assets/gif-js/.npmignore",
  "assets/gif-js/libgif.js",
  "typewriter.js",
  "style.css",
  "paddle.css",
  "index.html",
  "service-worker.js",
  "facelang.html",
  "pdfsplitter.html",
  "paddle.html",
  "manifest.json",
  "paddle.js",
  "imageconverter.html",
  "fight.js",
  "pdfeditor.css",
  "typewriter.ts",
  "script.js",
  "videoconverter.html",
  "imageconverter.css",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(urlsToCache))
  );
});

self.addEventListener("fetch", (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
self.addEventListener("activate", (event) => {
  const cacheWhitelist = [CACHE_NAME];
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.map((key) => {
          if (!cacheWhitelist.includes(key)) return caches.delete(key);
        })
      )
    )
  );
});
